[BaseMap]
AttributeTable=SulutRoads.tbt
CoordSystem=unknown.csy
CoordBounds=492168.48800000001 14234.648000000001 793690.3600000001 219708.22000000003
Domain=SulutRoads.mps
DomainInfo=SulutRoads.mps;Long;UniqueID;0;;
Type=SegmentMap
Proximity=1027.367860
[Ilwis]
Description=SegmentMapRelate(SulutRoads.mps,SulutCitiesBuffered2Km.mpa,intersects,false)
Time=1495550724
Version=3.1
Class=Dependent Segment Map
Type=BaseMap
[SegmentMap]
Snap Distance=3015.218720
Tunnel Width=301.521872
Type=SegmentMapVirtual
[IlwisObjectVirtual]
Expression=SegmentMapRelate(SulutRoads.mps,SulutCitiesBuffered2Km.mpa,intersects,false)
DefOnlyPossible=No
[ObjectDependency]
NrDepObjects=2
Object0=SulutRoads.mps
Object1=SulutCitiesBuffered2Km.mpa
[SegmentMapVirtual]
Expression=SegmentMapRelate(SulutRoads.mps,SulutCitiesBuffered2Km.mpa,intersects,false)
Type=SegmentMapRelate
[SegmentMapRelate]
InputMap1=SulutRoads.mps
InputMap2=SulutCitiesBuffered2Km.mpa
Relation=intersects
Negation=No
[SegmentMapStore]
Status=-32767
Format=2
Segments=391
DeletedSegments=0
Coordinates=0
[Table]
Description=
Time=1495550724
Version=3.1
Class=Table
Domain=None.dom
DomainInfo=none.dom;Byte;none;0;;
Columns=5
Records=391
Type=TableStore
[TableStore]
Data=SulutRoadsIntersectsSulutCitiesBuffered2Km.mps#
UseAs=No
Col0=MinCoords
Col1=MaxCoords
Col2=Coords
Col3=Deleted
Col4=SegmentValue
Type=TableBinary
[Col:MinCoords]
Description=
Time=1495550724
Version=3.1
Class=Column
Domain=unknown.csy
DomainInfo=unknown.csy;Coord;coord;0;;
ReadOnly=No
OwnedByTable=Yes
StoreType=Coord
Stored=Yes
Type=ColumnStore
[Col:MaxCoords]
Description=
Time=1495550724
Version=3.1
Class=Column
Domain=unknown.csy
DomainInfo=unknown.csy;Coord;coord;0;;
ReadOnly=No
OwnedByTable=Yes
StoreType=Coord
Stored=Yes
Type=ColumnStore
[Col:Coords]
Description=
Time=1495550724
Version=3.1
Class=Column
Domain=CoordBuf.dom
DomainInfo=CoordBuf.dom;?;coordbuf;0;;
ReadOnly=No
OwnedByTable=No
StoreType=CoordBuf
Stored=Yes
Type=ColumnStore
[Col:Deleted]
Description=
Time=1495550724
Version=3.1
Class=Column
Domain=bool.dom
DomainInfo=bool.dom;Byte;bool;0;;
Range=0:1:offset=-1
ReadOnly=No
OwnedByTable=No
Sum=?
Mean=?
StdDev=?
StoreType=Long
Stored=Yes
Type=ColumnStore
[Col:SegmentValue]
Description=
Time=1495550724
Version=3.1
Class=Column
Domain=SulutRoads.mps
DomainInfo=SulutRoads.mps;Long;UniqueID;0;;
ReadOnly=No
OwnedByTable=No
StoreType=Long
Stored=Yes
Type=ColumnStore
